import type { Metadata } from "next";
import { Borel, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import JotaiProvider from "./Component/jotaiProvider";

const borel = Borel({
  variable: "--font-borel",
  subsets: ["latin"],
  weight: "400", // Added weight property
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      className={`${borel.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}

      >
        {children}
      </body>
    </html>
  );
}
